### ISSUE TITLE
Radial Inventory System V3でMaterialの切り替えがうまくいかない

### ISSUE THREAD

**Issue by yutter-vrc** [Yagihata/RadialInventorySystemV3#4]
3つ以上のMaterialをtoggleで入れ替える際、間に設定されているMaterialの切り替えがうまくいかない
ex.
Material1、Material2、Material3をそれぞれ切り替える時、「プロップ一覧」に上から項目をセットする。
Material1
Material2
Material3

この時、Material1->Material3やMaterial3->Material1、Material2->Material1のような切り替えはうまくいくが、
Material1->Material2、Material3->Material2のように間にある項目へ切り替えようとすると動作しない。

使用SDK：VRCSDK3-AVATAR-2021.05.21.12.13_Public
Unity ver：Unity 2018.4.20f1

**Comment by Yagihata** [comment]
マテリアルをいじるAnimatorControllerLayerは、他のマテリアルをいじるLayerのウェイトをゼロにする。
それか、マテリアル初期化のレイヤーを統一させることで解決しそう？

**Comment by Yagihata** [comment]
7bcda89 で多分直ったはず
